[package]
name = "sudoku"
version = "0.1.0"
authors = ["Marcelo Lima <marcelowind@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
clap = "3.0.0-beta.1"
crossbeam = "0.7"
crossbeam-utils = "0.7"
rand = "0.7"

[build-dependencies]
rustc_version = "0.2"
